### ISSUE TITLE
Hide "calendar panel" and enable selection of date range only from presets options.

### ISSUE THREAD

**Issue by vasanthid** [predixdesignsystem/px-rangepicker#15]

**Comment by randyaskin** [comment]
Hi @vasanthid, couldn't you just use a plain old px-dropdown for this?

**Comment by benoitjchevalier** [comment]
We had a quick discussion about this yesterday, the idea being to keep using the px-datetime-presets components so that the whole json config and events don't have to be done again. Not sure how easy it would be to stick it in a dropdow, but the idea would be similar: stick a presets component in something and hook it to rangepicker/rangefield
